server:
  port: 8088
  tomcat:
    uri-encoding: utf-8
spring:
  datasource:
    url: jdc:mysql://localhost:3306/test?characterEncoding=utf8
    username: root
    password: eplugger
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hinernate.dialect.MySQL5Dialect